### PR TITLE
Warn against name collisions when defining types

### PR DESCRIPTION
**Pull request by lorefnon**
Resolves https://github.com/stepci/garph/issues/84

### CODE REVIEW

**Comment by mishushakov** [comment]
Nice catch. But instead of making a new set, can't you just `this.types.find(x => x.typeDef.name === name)`?

**Comment by lorefnon** [comment]
I can do that if you prefer. I was just avoiding the full list iteration over every defined type for every new type added.

**Comment by mishushakov** [comment]
It's ok in this case

**Comment by mishushakov** [comment]
Looks good, does the relay example still work?
Could you also throw an error instead console.warn and console.trace, I think it would be more appropriate 🙏

**Comment by lorefnon** [comment]
Then it will need to be a breaking change ?

**Comment by mishushakov** [comment]
Sorry, can you elaborate?

**Comment by lorefnon** [comment]
Basically name collisions lead to a runtime error only in some cases right now. 

So it is for example possible to do something like: 

```ts
let UserT = g.type("User", { ... })

if (isUserAdmin) {
    UserT = g.type("User", { ... })
}
```

Now that it throws, above usage will fail. This is obviously not something most users will be affected by, so you can take a call on whether to release this as breaking or not.

---

The relay example runs fine.

**Comment by mishushakov** [comment]
How does this behaviour work in Pothos or GraphQL.js or other framework?

**Comment by lorefnon** [comment]
Most folks who use GraphQL.js, generate code from SDL. The official SDL parser has performs validations that disallow duplicate names. 

```
> require("graphql").buildSchema(`
... type Foo {
...     name: String!
... }
... type Foo {
...     age: Int!
... }
... type Query {
...     foo: Foo
... }
... `)
Uncaught Error: There can be only one type named "Foo".
    at assertValidSDL (/home/lorefnon/Workspace/garph/node_modules/graphql/validation/validate.js:135:11)
    at buildASTSchema (/home/lorefnon/Workspace/garph/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at Object.buildSchema (/home/lorefnon/Workspace/garph/node_modules/graphql/utilities/buildASTSchema.js:109:10)
```

Being a low level library, it offers ways to bypass these validations, but by default SDL based code generators will not allow duplicate names. 

I haven't used Pothos myself, but looking at the code, it too [throws](https://github.com/hayes/pothos/blob/main/packages/deno/packages/core/config-store.ts#L147) for duplicate names at the time of registration.

**Comment by mishushakov** [comment]
Yeah, in this case we should throw too. Can you submit an updated patch?

Happy New Year 🥳

**Comment by lorefnon** [comment]
Hey, I updated this to throw a while back. We can merge if nothing else is needed.

**Comment by lorefnon** [comment]
Wish you too a happy new year 🙂

**Comment by mishushakov** [comment]
I've just changed this.types to Map 😄

**Pull request merged**
